version: '3'

services:
  server:
    container_name: nodejs
    build: '.'
    volumes:
      - ./:/node-app
      - ./node_modules:/node-app/node_modules
    environment:
      NODE_ENV: development
    depends_on:
      - mongo
    links:
      - mongo
    ports:
      - '9000:9000'
      - '8080:8080'

  mongo:
    image: 'mongo'
    container_name: mongo
    ports:
      - '27017:27017'
    volumes:
      - ./data/db:/data/db